---
# file: roles/postgresql_server/tasks/main.yml

- name: add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
  tags:
      - postgres

- name: add PostgreSQL key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  tags:
      - postgres

- name: install PostgreSQL via apt
  apt: name={{ item }} force=yes
  with_items:
    - postgresql-9.1
    - python-psycopg2
    - libpostgresql-jdbc-java
  tags:
    - postgres

- name: install PostgreSQL contrib via apt
  apt: name=postgresql-contrib-9.1 force=yes
