---
# file: roles/cdh_hadoop_config/handlers/main.yml

- name: restart hadoop-hdfs-namenode
  service: name=hadoop-hdfs-namenode state=restarted
  ignore_errors: yes

- name: restart hadoop-hdfs-datanode
  service: name=hadoop-hdfs-datanode state=restarted
  ignore_errors: yes

- name: restart hadoop-hdfs-journalnode
  service: name=hadoop-hdfs-journalnode state=restarted
  ignore_errors: yes

- name: restart hadoop-mapreduce-historyserver
  service: name=hadoop-mapreduce-historyserver state=restarted
  ignore_errors: yes

- name: restart hadoop-yarn-nodemanager
  service: name=hadoop-yarn-nodemanager state=restarted
  ignore_errors: yes

- name: restart hadoop-yarn-resourcemanager
  service: name=hadoop-yarn-resourcemanager state=restarted
  ignore_errors: yes

- name: refresh datanodes
  sudo_user: hdfs
  command: hdfs dfsadmin -refreshNodes
  ignore_errors: yes