---
# file: roles/apache2/tasks/main.yml

- name: install apache2 via apt
  apt: pkg={{ item }}
  with_items:
     - apache2
  tags: apache

- name: configure apache2 so it doesn't complain 'can't determine fqdn'
  lineinfile: dest=/etc/apache2/apache2.conf regexp="{{ ansible_hostname }}" line="ServerName {{ ansible_hostname }}"
  tags: apache