---
# file: roles/rsylog_fluentd/tasks/main.yml

- name: configure fluentd in /etc/rsyslog.d/
  template: src={{ item }} dest=/etc/rsyslog.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - 99-fluentd.conf
  tags:
    - rsyslog
    - fluentd
  notify:
    - restart rsyslog
    - log installation message