---
# file: roles/logstash_index_cleaner/tasks/main.yml

- name: install python-pip via apt
  apt: pkg=python-pip
  tags: logstash_index_cleaner

- name: clone the expire-logs repo to /var/lib/logstash-index-cleaner
  shell: creates=/var/lib/logstash-index-cleaner chdir=/tmp curl https://api.github.com/repos/logstash/expire-logs/tarball | tar xz && mv expire-logs-master /var/lib/logstash-index-cleaner
  tags: logstash_index_cleaner

- name: pip install -r requirements.txt
  shell: chdir=/var/lib/logstash-index-cleaner pip install -r requirements.txt
  tags: logstash_index_cleaner

- name: install the logstash index cleaner crontab at /etc/cron.d/logstash-index-cleaner
  template: src=logstash-index-cleaner.cron.d dest=/etc/cron.d/logstash-index-cleaner owner=root group=root mode=644
  tags: logstash_index_cleaner