---
# file: roles/presto_common/tasks/main.yml

- name: Make sure the /data/presto directory exists
  file: path=/data/presto state=directory
  tags: presto

- name: Make sure the /usr/local/presto directory exists
  file: path=/usr/local/presto state=directory
  tags: presto

- name: Make sure an /usr/local/presto/etc directory exists
  file: path=/usr/local/presto/etc state=directory
  tags: presto

- name: Make sure an /usr/local/presto/etc/catalog directory exists
  file: path=/usr/local/presto/etc/catalog state=directory
  tags: presto

- name: Make sure Presto is available at /usr/local/presto
  shell: creates=/usr/local/presto/bin/launcher chdir=/tmp curl http://search.maven.org/remotecontent?filepath=com/facebook/presto/presto-server/0.52/presto-server-0.52.tar.gz | tar xz && mv presto-server-0.52/* /usr/local/presto
  tags: presto

- name: Make sure Presto is configured
  template: src={{ item }} dest=/usr/local/presto/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - node.properties
    - jvm.config
  tags: presto

- name: Make sure Presto Hive Catalog is configured
  template: src={{ item }} dest=/usr/local/presto/etc/catalog/{{ item }} owner=root group=root mode=0644
  with_items:
    - jmx.properties
    - hive.properties
  tags: presto