---
# file: roles/presto_common/tasks/main.yml

- name: create the /data/presto directory
  file: path=/data/presto state=directory
  tags: presto

- name: create the /usr/lib/presto/etc directory
  file: path=/usr/lib/presto/etc state=directory
  tags: presto

- name: create the /usr/lib/presto/etc/catalog directory
  file: path=/usr/lib/presto/etc/catalog state=directory
  tags: presto

- name: install Presto at /usr/lib/presto
  shell: creates=/usr/lib/presto/bin/launcher chdir=/tmp curl http://central.maven.org/maven2/com/facebook/presto/presto-server/0.65/presto-server-0.65.tar.gz | tar xz && mv presto-server-0.65/* /usr/lib/presto
  tags: presto

- name: configure presto in /usr/lib/presto/etc
  template: src={{ item }} dest=/usr/lib/presto/etc/{{ item }} owner=root group=root mode=0644
  with_items:
    - node.properties
    - jvm.config
  tags:
    - configuration
    - presto

- name: configure presto hive catalog in /usr/lib/presto/etc/catalog
  template: src={{ item }} dest=/usr/lib/presto/etc/catalog/{{ item }} owner=root group=root mode=0644
  with_items:
    - jmx.properties
    - hive.properties
    - tpch.properties
  tags:
    - configuration
    - presto

- name: install presto command line client
  shell: chdir=/usr/bin curl -o presto http://central.maven.org/maven2/com/facebook/presto/presto-cli/0.65/presto-cli-0.65-executable.jar && chmod +x presto
  tags: presto

- name: install upstart config for presto
  template: src=upstart.conf dest=/etc/init/presto.conf owner=root group=root mode=0644
  tags:
    - configuration
    - presto