---
# file: roles/common/tasks/main.yml

- name: upgrade all safe packages
  apt: upgrade=safe update_cache=yes

- name: mount / with inode_readahead_blks=128,noatime,errors=remount-ro
  shell: creates=/etc/fstab.bak chdir=/etc cp fstab fstab.bak && sed -i "s/ errors=remount-ro/ inode_readahead_blks=128,noatime,errors=remount-ro/" fstab

- name: configure /etc/security/limits.conf with high max file descriptors (soft/hard)
  template: src=limits.conf dest=/etc/security/limits.conf mode=0644

- name: configure /etc/pam.d/common-session and /etc/pam.d/common-session-noninteractive with pam_limits.so
  lineinfile: name={{ item }} regexp='pam_limits.so' line='session required pam_limits.so'
  with_items:
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive

- name: install commonly used packages via apt
  apt: pkg={{ item }}
  with_items:
    - checkinstall
    - htop
    - curl
    - net-tools
    - liblzo2-dev
    - zip

- name: install intel-microcode
  apt: pkg=intel-microcode
  when: '"Intel" in ansible_processor[0]'

- name: install amd64-microcode
  apt: pkg=amd64-microcode
  when: '"AMD" in ansible_processor[0] and ansible_architecture == "x86_64"'

- name: remove various useless files
  command: removes={{ item }} rm {{ item }}
  with_items:
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/51-cloudguest
    - /etc/update-motd.d/91-release-upgrade
    - /etc/update-motd.d/98-cloudguest

- name: create the hosts file for all machines
  template: src=hosts dest=/etc/hosts

- name: configure landscape-sysinfo to not show link
  template: src=client.conf dest=/etc/landscape/client.conf owner=root group=root mode=0644

- name: configure rsyslog with the imfile module
  template: src=rsyslog.conf dest=/etc/rsyslog.d/30-imfile.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog

- name: install NTP
  apt: pkg=ntp
  tags: ntp

- name: configure NTP in /etc/ntp.conf
  template: src=ntp.conf dest=/etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp

- name: make sure NTP is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp