---
# file: roles/common/tasks/main.yml

- name: mount / with inode_readahead_blks=128,noatime,errors=remount-ro
  shell: creates=/etc/fstab.bak chdir=/etc cp fstab fstab.bak && sed -i "s/ errors=remount-ro/ inode_readahead_blks=128,noatime,errors=remount-ro/" fstab

- name: write sysctl config file to /etc/sysctl.d/60-hadoop.conf
  template: src=sysctl.conf dest=/etc/sysctl.d/60-hadoop.conf owner=root group=root mode=0644
  notify:
    - restart procps

- name: configure /etc/security/limits.conf with high max file descriptors (soft/hard)
  template: src=limits.conf dest=/etc/security/limits.conf mode=0644

- name: configure /etc/pam.d/common-session and /etc/pam.d/common-session-noninteractive with pam_limits.so
  lineinfile: name={{ item }} regexp='pam_limits.so' line='session required pam_limits.so'
  with_items:
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive

- name: install commonly used packages via apt
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - checkinstall
    - htop
    - curl
    - net-tools
    - liblzo2-dev
    - zip
    - python-pycurl
    - software-properties-common

- name: install intel-microcode
  apt: pkg=intel-microcode
  when: (ansible_virtualization_role is not defined or ansible_virtualization_role == "host") and "Intel" in ansible_processor[0]

- name: install amd64-microcode
  apt: pkg=amd64-microcode
  when: (ansible_virtualization_role is not defined or ansible_virtualization_role == "host") and "AMD" in ansible_processor[0]

- name: remove various useless files
  command: removes={{ item }} rm {{ item }}
  with_items:
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/91-release-upgrade

- name: create the hosts file for all machines
  template: backup=yes src=hosts dest=/etc/hosts

- name: configure landscape-sysinfo to not show link
  template: src=client.conf dest=/etc/landscape/client.conf owner=root group=root mode=0644

- name: configure rsyslog with the imfile module
  template: src=rsyslog.conf dest=/etc/rsyslog.d/30-imfile.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog

- name: install NTP
  apt: pkg=ntp
  tags: ntp

- name: configure NTP in /etc/ntp.conf
  template: src=ntp.conf dest=/etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp

- name: make sure NTP is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp