---
# file: roles/td_agent/tasks/main.yml

- name: add Treasure Data repository
  apt_repository: repo='deb http://packages.treasure-data.com/precise/ precise contrib'
  tags: tdagent

- name: install libssl0.9.8 for Debian "wheezy"
  script: install_debian_libssl0.9.8.sh
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "wheezy"
  tags: tdagent

- name: install td-agent and libcurl via apt
  apt: pkg={{ item }} update_cache=yes force=yes
  with_items:
    - td-agent
    - libcurl3
    - libcurl3-gnutls
    - libcurl4-openssl-dev
  tags: tdagent

- name: remove older fluent Elasticsearch plugin versions v0.1.*
  shell: rm -Rf /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.1.*
  ignore_errors: yes
  tags: tdagent

- name: remove older fluent Elasticsearch plugin versions v0.2.0
  command: removes=/usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.2.0 rm -Rf /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.2.0
  tags: tdagent

- name: install the fluent Elasticsearch plugin
  command: creates=/usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.3.0/Gemfile /usr/lib/fluent/ruby/bin/fluent-gem install fluent-plugin-elasticsearch
  tags: tdagent

- name: install the fluent tail-multiline plugin
  command: creates=/usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-tail-multiline-0.1.5/Gemfile /usr/lib/fluent/ruby/bin/fluent-gem install fluent-plugin-tail-multiline
  tags: tdagent

- name: configure td-agent in /etc/td-agent/td-agent.conf
  template: src=td-agent.conf dest=/etc/td-agent/td-agent.conf owner=root group=root mode=0644
  tags: tdagent
  notify:
    - restart td-agent