---
# file: roles/td_agent/tasks/main.yml

- name: add Treasure Data repository
  apt_repository: repo='deb http://packages.treasure-data.com/precise/ precise contrib'
  tags: tdagent

- name: install td-agent via apt
  apt: pkg=td-agent update_cache=yes force=yes
  tags: tdagent

- name: remove older fluent Elasticsearch plugin versions
  command: rm -Rf /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.1.*
  ignore_errors: yes

- name: install the fluent Elasticsearch plugin
  shell: creates=/usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-elasticsearch-0.2.0/Gemfile /usr/lib/fluent/ruby/bin/fluent-gem install fluent-plugin-elasticsearch
  tags: tdagent

- name: configure td-agent in /etc/td-agent/td-agent.conf
  template: src=td-agent.conf dest=/etc/td-agent/td-agent.conf owner=root group=root mode=0644
  tags: tdagent
  notify:
    - restart td-agent