---
# file: roles/mysql_server/tasks/main.yml

- name: predefine MySQL root passwd
  shell: executable=/bin/bash debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password password hive_{{ site_name }}"

- name: predefine MySQL root passwd confirm
  shell: executable=/bin/bash debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password_again password hive_{{ site_name }}"

- name: install MySQL via apt
  apt: name={{ item }}
  with_items:
    - mysql-server-5.5
    - libmysql-java
    - python-mysqldb
  tags:
    - mysql