---
# file: roles/ganglia_monitor/tasks/main.yml

- name: Make sure Ganglia Monitor is installed
  apt: name=$item
  with_items:
    - sysstat
    - php5-cli
    - ganglia-monitor
    - hddtemp
  tags: ganglia

- name: Make sure our customized gmond.conf is available under /etc/ganglia/gmond.conf
  template: src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root mode=0644
  tags: ganglia
  notify:
    - restart ganglia-monitor

- name: Make sure the device-metrics script is available at /usr/local/sbin
  template: src=device-metrics.php dest=/usr/local/sbin/device-metrics.php owner=root group=root mode=0644
  tags: ganglia

- name: Make sure the device-metrics crontab is available at /etc/cron.d/device-metrics
  template: src=device-metrics.cron.d dest=/etc/cron.d/device-metrics owner=root group=root mode=644
  tags: ganglia